In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../stock_data_all/Finance/0/ABCB.csv")

In [3]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,Close_SMA5,Close_SMA20,Close_SMA60,...,TSM,ASML,STM,SAP,YNDX,NTDOY,PCRFF,JD,TSHTY,IFNNY
0,1995-02-02,5.116502,5.167161,4.863210,5.116502,2.902049,25169,5.116502,4.984790,5.092017,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
1,1995-02-03,5.167161,5.167161,5.167161,5.167161,2.930782,494,5.116502,4.999988,5.086951,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
2,1995-02-06,5.167161,5.167161,5.167161,5.167161,2.930782,3701,5.116502,5.015185,5.083574,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
3,1995-02-07,4.964527,4.964527,4.964527,4.964527,2.815850,2468,5.096239,5.020251,5.076820,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
4,1995-02-08,4.863210,4.863210,4.863210,4.863210,2.758385,1974,5.055712,5.010120,5.066688,...,0.000000,0.000000,4.229167,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391,2024-06-13,48.480000,48.520000,47.090000,47.669998,47.669998,250100,47.534000,48.264500,47.808333,...,172.910004,1052.709961,44.250000,192.419998,18.940001,13.24,8.21,29.400000,10.0,40.700001
7392,2024-06-14,46.889999,47.110001,46.490002,46.790001,46.790001,240600,47.376000,48.092000,47.795000,...,172.509995,1027.900024,42.459999,187.820007,18.940001,13.39,8.21,28.770000,10.0,39.099998
7393,2024-06-17,46.709999,47.869999,46.709999,47.840000,47.840000,298600,47.558000,47.961500,47.786000,...,177.240005,1052.469971,43.099998,190.020004,18.940001,13.37,8.09,29.240000,10.0,39.180000
7394,2024-06-18,47.580002,48.619999,47.580002,48.160000,48.160000,255700,47.824000,47.892500,47.805500,...,179.690002,1061.380005,43.080002,188.619995,18.940001,13.79,8.07,29.049999,10.0,38.779999
7395,2024-06-20,47.820000,48.349998,47.610001,47.939999,47.939999,581600,47.680000,47.805500,47.823667,...,175.380005,1050.739990,40.680000,191.470001,18.940001,13.30,8.13,28.680000,10.0,37.189999

In [4]:
data.iloc[:, 1:]

,Open,High,Low,Close,Adj Close,Volume,Close_SMA5,Close_SMA20,Close_SMA60,Close_SMA120,...,TSM,ASML,STM,SAP,YNDX,NTDOY,PCRFF,JD,TSHTY,IFNNY
0,5.116502,5.167161,4.863210,5.116502,2.902049,25169,5.116502,4.984790,5.092017,5.221829,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
1,5.167161,5.167161,5.167161,5.167161,2.930782,494,5.116502,4.999988,5.086951,5.219296,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
2,5.167161,5.167161,5.167161,5.167161,2.930782,3701,5.116502,5.015185,5.083574,5.218452,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
3,4.964527,4.964527,4.964527,4.964527,2.815850,2468,5.096239,5.020251,5.076820,5.215919,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
4,4.863210,4.863210,4.863210,4.863210,2.758385,1974,5.055712,5.010120,5.066688,5.211698,...,0.000000,0.000000,4.229167,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391,48.480000,48.520000,47.090000,47.669998,47.669998,250100,47.534000,48.264500,47.808333,48.410833,...,172.910004,1052.709961,44.250000,192.419998,18.940001,13.24,8.21,29.400000,10.0,40.700001
7392,46.889999,47.110001,46.490002,46.790001,46.790001,240600,47.376000,48.092000,47.795000,48.369583,...,172.509995,1027.900024,42.459999,187.820007,18.940001,13.39,8.21,28.770000,10.0,39.099998
7393,46.709999,47.869999,46.709999,47.840000,47.840000,298600,47.558000,47.961500,47.786000,48.330583,...,177.240005,1052.469971,43.099998,190.020004,18.940001,13.37,8.09,29.240000,10.0,39.180000
7394,47.580002,48.619999,47.580002,48.160000,48.160000,255700,47.824000,47.892500,47.805500,48.285417,...,179.690002,1061.380005,43.080002,188.619995,18.940001,13.79,8.07,29.049999,10.0,38.779999
7395,47.820000,48.349998,47.610001,47.939999,47.939999,581600,47.680000,47.805500,47.823667,48.237083,...,175.380005,1050.739990,40.680000,191.470001,18.940001,13.30,8.13,28.680000,10.0,37.189999

In [3]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data_ = scaler.fit_transform(data.iloc[:, 1:].values)

In [7]:
data_.shape

(7396, 71)

In [9]:
data["Close"]

,Date,Open,High,Low,Close,Adj Close,Volume,Close_SMA5,Close_SMA20,Close_SMA60,...,TSM,ASML,STM,SAP,YNDX,NTDOY,PCRFF,JD,TSHTY,IFNNY
0,1995-02-02,5.116502,5.167161,4.863210,5.116502,2.902049,25169,5.116502,4.984790,5.092017,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
1,1995-02-03,5.167161,5.167161,5.167161,5.167161,2.930782,494,5.116502,4.999988,5.086951,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
2,1995-02-06,5.167161,5.167161,5.167161,5.167161,2.930782,3701,5.116502,5.015185,5.083574,...,0.000000,0.000000,4.208333,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
3,1995-02-07,4.964527,4.964527,4.964527,4.964527,2.815850,2468,5.096239,5.020251,5.076820,...,0.000000,0.000000,4.187500,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
4,1995-02-08,4.863210,4.863210,4.863210,4.863210,2.758385,1974,5.055712,5.010120,5.066688,...,0.000000,0.000000,4.229167,0.000000,0.000000,0.00,0.00,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391,2024-06-13,48.480000,48.520000,47.090000,47.669998,47.669998,250100,47.534000,48.264500,47.808333,...,172.910004,1052.709961,44.250000,192.419998,18.940001,13.24,8.21,29.400000,10.0,40.700001
7392,2024-06-14,46.889999,47.110001,46.490002,46.790001,46.790001,240600,47.376000,48.092000,47.795000,...,172.509995,1027.900024,42.459999,187.820007,18.940001,13.39,8.21,28.770000,10.0,39.099998
7393,2024-06-17,46.709999,47.869999,46.709999,47.840000,47.840000,298600,47.558000,47.961500,47.786000,...,177.240005,1052.469971,43.099998,190.020004,18.940001,13.37,8.09,29.240000,10.0,39.180000
7394,2024-06-18,47.580002,48.619999,47.580002,48.160000,48.160000,255700,47.824000,47.892500,47.805500,...,179.690002,1061.380005,43.080002,188.619995,18.940001,13.79,8.07,29.049999,10.0,38.779999
7395,2024-06-20,47.820000,48.349998,47.610001,47.939999,47.939999,581600,47.680000,47.805500,47.823667,...,175.380005,1050.739990,40.680000,191.470001,18.940001,13.30,8.13,28.680000,10.0,37.189999

In [10]:
ten_day_change = data["Close"].pct_change(periods=10) * 100

In [11]:
ten_day_change

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
7391    0.020978
7392   -6.326326
7393   -0.020895
7394    1.818183
7395    0.820188
Name: Close, Length: 7396, dtype: float64

In [4]:
ten_day_change = data["Close"].pct_change(periods=10) * 100
# Define the fixed bins and labels
fixed_bins = [-float("inf"), -10, -2, 2, 10, float("inf")]
fixed_labels = [0, 1, 2, 3, 4]

# Discretize the '10_day_change' column based on fixed percentage change
data["10_day_change_fixed_discrete"] = pd.cut(
    ten_day_change, bins=fixed_bins, labels=fixed_labels
)

In [20]:
data["10_day_change_fixed_discrete"].iloc[10]

2

In [5]:
from sklearn.model_selection import train_test_split


def split_data(stock, lookback):
    data_raw = np.array(stock)
    n_time = len(data_raw)
    data, targets = [], []
    for index in range(n_time - lookback):
        data.append(data_raw[index : index + lookback, 1:-1])
        targets.append(stock["10_day_change_fixed_discrete"].iloc[index + lookback])

    data = np.array(data)
    targets = np.array(targets)
    print("總資料量:{}".format(data.shape))

    # 使用train_test_split函數分割訓練集與測試集
    x_train, x_test, y_train, y_test = train_test_split(
        data, targets, test_size=0.2, shuffle=True, random_state=42
    )

    return x_train, y_train, x_test, y_test


lookback = 60  # choose sequence length
x_train, y_train, x_test, y_test = split_data(data, lookback)
print("x_train.shape =", x_train.shape)
print("y_train.shape =", y_train.shape)
print("x_test.shape =", x_test.shape)
print("y_test.shape =", y_test.shape)

總資料量:(7336, 60, 71)
x_train.shape = (5868, 60, 71)
y_train.shape = (5868,)
x_test.shape = (1468, 60, 71)
y_test.shape = (1468,)

In [34]:
type(x_train[0][0][0])

float

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

use_cuda = 1
device = torch.device("cuda" if (torch.cuda.is_available() & use_cuda) else "cpu")
print(device)


def transform_type_train(x, device):
    return torch.Tensor(x.astype(float)).to(device)


def transform_type_test(y, device):
    return torch.Tensor(y.astype(int)).to(torch.int64).to(device)


x_train_ = transform_type_train(x_train, device)
x_test_ = transform_type_train(x_test, device)
y_train_ = transform_type_test(y_train, device)
y_test_ = transform_type_test(y_test, device)

cuda

In [7]:
train_ds = TensorDataset(x_train_, y_train_)
test_ds = TensorDataset(x_test_, y_test_)
train_dl = DataLoader(train_ds, batch_size=16, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=16, shuffle=False)

In [8]:
for batch_x, batch_y in train_dl:
    print(batch_x.shape, batch_y.shape)
    print(type(batch_x), type(batch_y))
    break

torch.Size([16, 60, 71]) torch.Size([16])
<class 'torch.Tensor'> <class 'torch.Tensor'>

cuda

In [31]:
class LSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, output_dim):
        super(LSTM, self).__init__()

        """
        input_dim: 輸入張量的維度 (每天的股價只會有一個值，所以維度為1)
        hidden_dim: 隱藏層的維度 (隱藏神經元數量)
        num_layers: LSTM的層數 (通常設定為1-3層)
        batch_first: 輸入張量的第一維是否為 batch_size (batch_size, seq_len, feature) 
                    ex: (1, 20, 1) => 20天的股價預測第21天的股價，每次訓練一批資料
        """
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.lstm = nn.LSTM(
            input_dim,
            hidden_dim,
            num_layers,
            batch_first=True,
            dropout=0.5,
            bidirectional=True,
        )
        self.fc = nn.Sequential(
            nn.Linear(hidden_dim * 2, 100),
            nn.ReLU(),
            nn.Dropout(p=0.5),
            nn.Linear(100, output_dim),
        )

    def forward(self, x):
        h0 = (
            torch.zeros(self.num_layers * 2, x.size(0), self.hidden_dim)
            .requires_grad_()
            .to(device)
        )
        c0 = (
            torch.zeros(self.num_layers * 2, x.size(0), self.hidden_dim)
            .requires_grad_()
            .to(device)
        )
        out, (hn, cn) = self.lstm(
            x, (h0.detach(), c0.detach())
        )  # out = (batch_size, sequence_length, hidden_dim)
        # print(f"after lstm layers, out = {out.shape}")
        out = self.fc(out[:, -1, :])  # 取最後一個時間點的輸出
        return out


# mymodel = LSTM(input_dim=1, hidden_dim=32, output_dim=1, num_layers=2)
# dummy_input = torch.randn(1, 10, 1)
# out = mymodel(dummy_input)
# torch.onnx.export(mymodel, dummy_input, "lstm_stock.onnx", opset_version=11)

In [32]:
input_dim = 71
hidden_dim = 500
num_layers = 5
output_dim = 5
num_epochs = 100
patience = 10

model = LSTM(
    input_dim=input_dim,
    hidden_dim=hidden_dim,
    output_dim=output_dim,
    num_layers=num_layers,
).to(device)
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=100, gamma=0.1)

In [11]:
device

device(type='cuda')

In [65]:
import time

start_time = time.time()
# hist = []
# for t in range(num_epochs):
#     y_train_pred = model(x_train_)
#     loss = criterion(y_train_pred, y_train_)
#     hist.append(loss.item())
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()
#     if t % 50 == 0:
#         print("Epoch ", t, "MSE: ", loss.item())

# training_time = time.time() - start_time
# print("Training time: {}".format(training_time))

Epoch  0 MSE:  1.5769619941711426
Epoch  50 MSE:  1.5532429218292236
Epoch  100 MSE:  1.5264134407043457
Epoch  150 MSE:  1.4856579303741455
Epoch  200 MSE:  1.4283955097198486
Epoch  250 MSE:  1.403802752494812
Epoch  300 MSE:  1.3992620706558228
Epoch  350 MSE:  1.3985151052474976
Epoch  400 MSE:  1.3986026048660278
Epoch  450 MSE:  1.3980807065963745
Training time: 15.831035137176514

In [16]:
import copy
import time

In [33]:
def train(model, num_epochs, train_dl, valid_dl, patience, device):

    loss_hist_train = [0] * num_epochs
    accuracy_hist_train = [0] * num_epochs
    loss_hist_valid = [0] * num_epochs
    accuracy_hist_valid = [0] * num_epochs

    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    min_valid_loss = np.inf

    for epoch in range(num_epochs):

        model.train()

        batch_num = 0

        for x_batch, y_batch in train_dl:

            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)

            batch_num += 1

            pred = model(x_batch)
            loss = criterion(pred, y_batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

            loss_hist_train[epoch] += loss.item() * y_batch.size(0)
            is_correct = (torch.argmax(pred, dim=1) == y_batch).float()
            accuracy_hist_train[epoch] += is_correct.sum().item()

        loss_hist_train[epoch] /= len(train_dl.dataset)
        accuracy_hist_train[epoch] /= len(train_dl.dataset)

        scheduler.step()

        model.eval()

        with torch.no_grad():

            for x_batch, y_batch in valid_dl:

                x_batch = x_batch.to(device)
                y_batch = y_batch.to(device)

                pred = model(x_batch)
                loss = criterion(pred, y_batch)
                loss_hist_valid[epoch] += loss.item() * y_batch.size(0)
                is_correct = (torch.argmax(pred, dim=1) == y_batch).float()
                accuracy_hist_valid[epoch] += is_correct.sum().item()

        loss_hist_valid[epoch] /= len(valid_dl.dataset)
        accuracy_hist_valid[epoch] /= len(valid_dl.dataset)

        if accuracy_hist_valid[epoch] > best_acc:
            best_acc = accuracy_hist_valid[epoch]
            best_model_wts = copy.deepcopy(model.state_dict())

        if epoch % 10 == 0:
            print(
                f"Epoch {epoch}:   Train accuracy: {accuracy_hist_train[epoch]:.4f}    Validation accuracy: {accuracy_hist_valid[epoch]:.4f} "
            )
            print(
                f"Epoch {epoch}:   Train loss: {loss_hist_train[epoch]:.4f}    Validation loss: {loss_hist_valid[epoch]:.4f} "
            )

        if loss_hist_valid[epoch] < min_valid_loss:
            counter = 0
        else:
            counter += 1

        if counter >= patience:
            break

    model.load_state_dict(best_model_wts)

    history = {}
    history["loss_hist_train"] = loss_hist_train
    history["loss_hist_valid"] = loss_hist_valid
    history["accuracy_hist_train"] = accuracy_hist_train
    history["accuracy_hist_valid"] = accuracy_hist_valid

    return model, history

In [34]:
start_time = time.time()
best_model, hist = train(model, num_epochs, train_dl, test_dl, patience, device)
training_time = time.time() - start_time
print("Training time: {}".format(training_time))

Epoch 0:   Train accuracy: 0.2900    Validation accuracy: 0.3386
Epoch 0:   Train loss: 1.4368    Validation loss: 1.3821
Epoch 10:   Train accuracy: 0.3102    Validation accuracy: 0.3413
Epoch 10:   Train loss: 1.4064    Validation loss: 1.3738
Epoch 20:   Train accuracy: 0.3131    Validation accuracy: 0.3338
Epoch 20:   Train loss: 1.3995    Validation loss: 1.3699
Epoch 30:   Train accuracy: 0.3206    Validation accuracy: 0.2970
Epoch 30:   Train loss: 1.3981    Validation loss: 1.3693
Epoch 40:   Train accuracy: 0.3183    Validation accuracy: 0.2977
Epoch 40:   Train loss: 1.3894    Validation loss: 1.3618
Epoch 50:   Train accuracy: 0.3095    Validation accuracy: 0.3399
Epoch 50:   Train loss: 1.3886    Validation loss: 1.3795

In [86]:
y_train_pred = model(x_train_)
y_train_pred = y_train_pred.detach().cpu().numpy()
is_correct = (np.argmax(y_train_pred, axis=1) == y_train).sum() / len(y_train_pred)

In [82]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

y_train_pred = model(x_train_)
y_train_pred = y_train_pred.detach().cpu().numpy()
predict = pd.DataFrame(scaler.inverse_transform(y_train_pred))
original = pd.DataFrame(scaler.inverse_transform(y_train_.detach().numpy()))

fig = plt.figure()
fig.subplots_adjust(hspace=0.2, wspace=0.2)

plt.subplot(1, 2, 1)
ax = sns.lineplot(x=original.index, y=original[0], label="Data", color="royalblue")
ax = sns.lineplot(
    x=predict.index, y=predict[0], label="Training Prediction (LSTM)", color="tomato"
)
ax.set_title("Stock price", size=14, fontweight="bold")
ax.set_xlabel("Days", size=14)
ax.set_ylabel("Cost (NTD)", size=14)
ax.set_xticklabels("", size=10)


plt.subplot(1, 2, 2)
ax = sns.lineplot(data=hist, color="royalblue")
ax.set_xlabel("Epoch", size=14)
ax.set_ylabel("Loss", size=14)
ax.set_title("Training Loss", size=14, fontweight="bold")
fig.set_figheight(6)
fig.set_figwidth(16)

ValueError: operands could not be broadcast together with shapes (5868,5) (71,) (5868,5)